const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Timer,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{TileMovement: 0},
	{Timer: 0},
	{Player: 0},
	{Solid: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Tilemap: 0},
	{Tilemap2: 0},
	{Sprite3: 0},
	{Tilemap3: 0},
	{Sprite4: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Tilemap6: 0},
	{Tilemap5: 0},
	{Tilemap7: 0},
	{Tilemap8: 0},
	{Tilemap10: 0},
	{Sprite11: 0},
	{Tilemap11: 0},
	{Sprite12: 0},
	{Tilemap9: 0},
	{Tilemap12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Tilemap13: 0},
	{Sprite17: 0},
	{Tilemap_Base: 0},
	{Tilemap4: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Tilemap14: 0},
	{Tilemap15: 0},
	{Sprite22: 0},
	{Tilemap16: 0},
	{Tilemap17: 0},
	{MoveTo: 0},
	{LineOfSight: 0},
	{Enemy: 0},
	{Keyboard: 0},
	{Pin: 0},
	{Sword: 0},
	{Chest: 0},
	{Trigger_zone: 0},
	{Audio: 0},
	{Mewo: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{GUI_MessageBox: 0},
	{GUI_Text: 0},
	{GUI_Enter: 0},
	{Message_Trigger: 0},
	{Score: 0},
	{Sprite32: 0},
	{Hourglass: 0},
	{Score_Hourglass: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Mewo_Zone: 0},
	{Mirror_Zone: 0},
	{Sprite23: 0},
	{Direction: 0},
	{Attack: 0},
	{Dead: 0},
	{Message_Showns: 0},
	{score: 0},
	{hourglass_score: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Tilemap6: class extends self.ITilemapInstance {},
	Tilemap5: class extends self.ITilemapInstance {},
	Tilemap7: class extends self.ITilemapInstance {},
	Tilemap8: class extends self.ITilemapInstance {},
	Tilemap10: class extends self.ITilemapInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Tilemap11: class extends self.ITilemapInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Tilemap9: class extends self.ITilemapInstance {},
	Tilemap12: class extends self.ITilemapInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Tilemap13: class extends self.ITilemapInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Tilemap_Base: class extends self.ITilemapInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Tilemap14: class extends self.ITilemapInstance {},
	Tilemap15: class extends self.ITilemapInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Tilemap16: class extends self.ITilemapInstance {},
	Tilemap17: class extends self.ITilemapInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sword: class extends self.ISpriteInstance {},
	Chest: class extends self.ISpriteInstance {},
	Trigger_zone: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Mewo: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	GUI_MessageBox: class extends self.ISpriteInstance {},
	GUI_Text: class extends self.ITextInstance {},
	GUI_Enter: class extends self.ITextInstance {},
	Message_Trigger: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Hourglass: class extends self.ISpriteInstance {},
	Score_Hourglass: class extends self.ITextInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Mewo_Zone: class extends self.ISpriteInstance {},
	Mirror_Zone: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {}
}