const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Anchor,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Hp: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{BG: 0},
	{Solid: 0},
	{Tiles: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Anchor: 0},
	{Biru: 0},
	{Spike: 0},
	{Coins: 0},
	{Coin_Effect: 0},
	{Dir: 0},
	{Runner: 0},
	{DeathEffect: 0},
	{DmgBox: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Touch: 0},
	{TiledBackground2: 0},
	{Text: 0},
	{Text2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Text3: 0},
	{Sprite6: 0},
	{Audio: 0},
	{Bullet: 0},
	{Text4: 0},
	{Score: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Tiles: class extends self.ITilemapInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Hp: class extends self.ISpriteInstance {},
	Biru: class extends self.ISpriteInstance {},
	Spike: class extends self.ITilemapInstance {},
	Coins: class extends self.ISpriteInstance {},
	Coin_Effect: class extends self.ISpriteInstance {},
	Runner: class extends self.ISpriteInstance {},
	DeathEffect: class extends self.ISpriteInstance {},
	DmgBox: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Text4: class extends self.ITextInstance {}
}