const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{spaceShooter: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Platform: 0},
	{pesawat: 0},
	{hp: 0},
	{Rotate: 0},
	{Bullet: 0},
	{Solid: 0},
	{meteor: 0},
	{laser: 0},
	{anemySpon: 0},
	{Particles: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Particles2: 0},
	{Sprite3: 0},
	{Audio: 0},
	{nyawaMusuh: 0},
	{alien: 0},
	{enemyspwan2: 0}
];

self.InstanceType = {
	spaceShooter: class extends self.ISpriteInstance {},
	pesawat: class extends self.ISpriteInstance {},
	meteor: class extends self.ISpriteInstance {},
	laser: class extends self.ISpriteInstance {},
	anemySpon: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	alien: class extends self.ISpriteInstance {},
	enemyspwan2: class extends self.ISpriteInstance {}
}