const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.EightDir,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Plugins.gamepad,
		C3.Behaviors.MoveTo,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Solid: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{movement: 0},
	{Jumpthru: 0},
	{"8Direction": 0},
	{enemy: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Button: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Sprite9: 0},
	{Platform: 0},
	{Sprite10: 0},
	{Gamepad: 0},
	{Sprite6: 0},
	{MoveTo: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Touch: 0},
	{Sprite15: 0},
	{Button2: 0},
	{Sprite16: 0},
	{HuaJuly_: 0},
	{Sprite17: 0},
	{Text: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Text2: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{movement2: 0},
	{enemy2: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{F_159154111_qOLUUAzaQZofRxYsmjoK5O61NqgeWZlC: 0},
	{Sprite5: 0},
	{Level1Button: 0},
	{Level1Text: 0},
	{Level2Button: 0},
	{Level2Text: 0},
	{lagu: 0},
	{TOMBOLMUSIK1: 0},
	{SOUND1: 0},
	{point: 0},
	{TScore: 0},
	{FGEnd: 0},
	{Restart: 0},
	{TEnd: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Text3: 0},
	{Text4: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Button2: class extends self.IButtonInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	HuaJuly_: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	enemy2: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	F_159154111_qOLUUAzaQZofRxYsmjoK5O61NqgeWZlC: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Level1Button: class extends self.ISpriteInstance {},
	Level1Text: class extends self.ITextInstance {},
	Level2Button: class extends self.ISpriteInstance {},
	Level2Text: class extends self.ITextInstance {},
	TOMBOLMUSIK1: class extends self.ISpriteInstance {},
	SOUND1: class extends self.ISpriteInstance {},
	point: class extends self.ISpriteInstance {},
	TScore: class extends self.ITextInstance {},
	FGEnd: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	TEnd: class extends self.ITextInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {}
}