const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Solid: 0},
	{Tanah: 0},
	{Spike: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Tween: 0},
	{Player: 0},
	{Touch: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Particles: 0},
	{Particles2: 0},
	{Audio: 0},
	{Finish: 0},
	{Win: 0},
	{BStart: 0},
	{Sine: 0},
	{Start: 0},
	{Text: 0},
	{BGCredit: 0},
	{Bullet: 0},
	{textcredit: 0},
	{Player2: 0},
	{Text2: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	Tanah: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	Finish: class extends self.ITiledBackgroundInstance {},
	Win: class extends self.ISpriteInstance {},
	BStart: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	BGCredit: class extends self.ISpriteInstance {},
	textcredit: class extends self.ITextInstance {},
	Player2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {}
}