const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Function,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Platform: 0},
	{Sine: 0},
	{nyan: 0},
	{Solid: 0},
	{pipa1: 0},
	{pipa2: 0},
	{gelombang: 0},
	{air: 0},
	{Mouse: 0},
	{Function: 0},
	{btnRestart: 0},
	{txtSkor: 0},
	{poin: 0},
	{Audio: 0},
	{Text: 0},
	{txtHighScore: 0},
	{Fade: 0},
	{Sprite: 0},
	{LocalStorage: 0},
	{btnResetHighscore: 0},
	{TiledBackground: 0},
	{Button: 0},
	{BPlay: 0},
	{TJudul: 0},
	{Tekan: 0},
	{highscore: 0},
	{skor: 0},
	{main: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	nyan: class extends self.ISpriteInstance {},
	pipa1: class extends self.ISpriteInstance {},
	pipa2: class extends self.ISpriteInstance {},
	gelombang: class extends self.ITiledBackgroundInstance {},
	air: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	btnRestart: class extends self.IButtonInstance {},
	txtSkor: class extends self.ITextInstance {},
	poin: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	txtHighScore: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	btnResetHighscore: class extends self.IButtonInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.IButtonInstance {},
	BPlay: class extends self.ISpriteInstance {},
	TJudul: class extends self.ITextInstance {},
	Tekan: class extends self.IInstance {}
}