const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Solid: 0},
	{aspal: 0},
	{batu: 0},
	{lantai: 0},
	{dinding: 0},
	{tanah: 0},
	{tembok: 0},
	{langit: 0},
	{tongsampah: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{playerkucing: 0},
	{kardus: 0},
	{npckucing: 0},
	{musuhDrone: 0},
	{npckucingNgomong: 0},
	{Anchor: 0},
	{scoreikan: 0},
	{scoregambarikan: 0},
	{nyawahati: 0},
	{gambarhati: 0},
	{mangkokmakanan: 0},
	{keyboard: 0},
	{score: 0},
	{backgroundhitampenutup: 0},
	{kucingpenutup2: 0},
	{dronepenutup: 0},
	{Bullet: 0},
	{penutupkata: 0},
	{tiledbackground: 0},
	{tekan: 0},
	{audio: 0},
	{pembuka: 0},
	{namagame: 0},
	{versi: 0},
	{Sine: 0},
	{Sine2: 0},
	{mulai: 0},
	{selamat: 0},
	{picelcreategambar: 0},
	{terimaHsih: 0},
	{kucingCokelatPenutup: 0},
	{Nyawa: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	aspal: class extends self.ISpriteInstance {},
	batu: class extends self.ISpriteInstance {},
	lantai: class extends self.ISpriteInstance {},
	dinding: class extends self.ISpriteInstance {},
	tanah: class extends self.ISpriteInstance {},
	tembok: class extends self.ISpriteInstance {},
	langit: class extends self.ISpriteInstance {},
	tongsampah: class extends self.ISpriteInstance {},
	playerkucing: class extends self.ISpriteInstance {},
	kardus: class extends self.ISpriteInstance {},
	npckucing: class extends self.ISpriteInstance {},
	musuhDrone: class extends self.ISpriteInstance {},
	npckucingNgomong: class extends self.ITextInstance {},
	scoreikan: class extends self.ITextInstance {},
	scoregambarikan: class extends self.ISpriteInstance {},
	nyawahati: class extends self.ITextInstance {},
	gambarhati: class extends self.ISpriteInstance {},
	mangkokmakanan: class extends self.ISpriteInstance {},
	keyboard: class extends self.IInstance {},
	score: class extends self.ISpriteInstance {},
	backgroundhitampenutup: class extends self.ISpriteInstance {},
	kucingpenutup2: class extends self.ISpriteInstance {},
	dronepenutup: class extends self.ISpriteInstance {},
	penutupkata: class extends self.ITextInstance {},
	tiledbackground: class extends self.ITiledBackgroundInstance {},
	tekan: class extends self.IInstance {},
	audio: class extends self.IInstance {},
	pembuka: class extends self.ISpriteInstance {},
	namagame: class extends self.ITextInstance {},
	versi: class extends self.ITextInstance {},
	mulai: class extends self.ISpriteInstance {},
	selamat: class extends self.ISpriteInstance {},
	picelcreategambar: class extends self.ISpriteInstance {},
	terimaHsih: class extends self.ITextInstance {},
	kucingCokelatPenutup: class extends self.ISpriteInstance {}
}